### ISSUE TITLE
Optimising Java solution for 242 question of leetcode

### ISSUE THREAD

**Issue by sarapapa-sp** [RajkumarSony/LeetCode-Solutions#25]

**Comment by sarapapa-sp** [comment]
@RajkumarSony  can you assign me this issue

**Comment by RajkumarSony** [comment]
Dear Contributor,

Thank you so much for approaching me with some issues. I am happy to allow you to optimize the solution.

Thank you.

**Comment by RajkumarSony** [comment]
Dear Contributor,

Thank you so much for approaching me with some issues. I am happy to allow you to optimize the required solution.
Reach me freely, If you need any help or suggestions.

Thank You.
