### ISSUE TITLE
I want to contribute the code for leetcode medium problem "Remove Nth Node From End of List" in cpp

### ISSUE THREAD

**Issue by AUM-PATEL2624** [RajkumarSony/LeetCode-Solutions#36]

**Comment by RajkumarSony** [comment]
Dear Contributor,

Okay, Thank you. You can pull/merge requests. And Kindly Start ⭐ this repo. and Add your information in PARTICIPANTS.md file. After that only your PRs will be accepted. Don't avoid it.

Thank You.

**Comment by RajkumarSony** [comment]
Dear Contributor,

Okay, Thank you. You can pull/merge requests. And Kindly Start ⭐ this repo. and Add your information in PARTICIPANTS.md file. After that only your PRs will be accepted. Don't avoid it.

Thank You.
